IlhadeTestes_MapScripts::
	.byte 0


PortaTrancada::
# 4 "data/maps/IlhadeTestes/scripts.pory"
	lock
# 5 "data/maps/IlhadeTestes/scripts.pory"
	msgbox PortaTrancada_Text_0
# 10 "data/maps/IlhadeTestes/scripts.pory"
	release
	end


PortaTrancada_Text_0:
# 5 "data/maps/IlhadeTestes/scripts.pory"
	.string "Esta porta está trancada.\n"
	.string "Se você viu isso, o teste é\l"
	.string "um sucesso!\p"
	.string "ÃÕãõ éáíóúàôâÔÂÊê…$"
